### ISSUE TITLE
Maybe has an error on windows

### ISSUE THREAD

**Issue by duydq12** [SYSTRAN/storages#60]
https://github.com/SYSTRAN/storages/blob/2fedd9200c66294d0396c00437c03b19b5523cd3/systran_storages/storage.py#L41-L44

I think it maybe has an error on windows
example:

```
path = "C:\User\abc"
fields = path.split(':', 1)
storage_id = "C"
path = "\User\abc"
```

I have 2 suggestions:

1. Change pattern define storage_id and path from storage_id:path to storage_id(other punct)path

2. Update code
```
if storage_id is None:
    if not os.path.exists(path):
        fields = path.split(':', 1)
        if len(fields) == 2:
                storage_id = fields[0]
                path = fields[1]
```

**Comment by guillaumekln** [comment]
I suggest to check if `storage_id` is a single character. In that case, we should use the original and complete `path`.
